### ISSUE TITLE
VIPS-warning

### ISSUE THREAD

**Issue by maxvoltar** [maxvoltar/photo-stream#26]
On generating, occasionally I see this error pop up in the log:

`(jekyll:13997): VIPS-WARNING **: 23:54:32.744: bad exif meta "exif-ifd3-GPSVersionID"`

**Comment by maxvoltar** [comment]
@benubois any ideas? Still seeing them even though everything seems to generate as expected.

**Comment by benubois** [comment]
Yeah, was wondering about that too. I think the [Windowstill.jpg image from the Leica](https://github.com/maxvoltar/photo-stream/blob/e14c88dd61180aa24369704b18d50bb188a9d00f/photos/original/Windowstill.jpg) is triggering it.

[Sounds like it's a bug in libexif](https://github.com/libvips/libvips/issues/394#issuecomment-359780578) and is probably nothing to worry about since it doesn't affect the build.

**Comment by maxvoltar** [comment]
Alright, I'll keep an eye on that libexif bug!
